---
- name: show running-config
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: running
      ios_command:
        commands:
          - show run
          - show ip int brief

      register: print_output

    -  debug: var=print_output.stdout_lines